src/BZ/BlogBundle/Entity/FileRequete.php
<?php
// src/BZ/BlogBundle/Entity/FileRequete.php
namespace BZ\BlogBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
// N'oubliez pas ce use :
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
* BZ\BlogBundle\Entity\FileRequete
*
* @ORM\Table()
* @ORM\Entity(repositoryClass="BZ\BlogBundle\Entity\FileRequeteRepository")
* @ORM\HasLifecycleCallbacks
*/
class FileRequete
{

    /**
    * @var integer $id
    *
    * @ORM\Column(name="id", type="integer")
    * @ORM\Id
    * @ORM\GeneratedValue(strategy="AUTO")
    */
    private $id;
    /**
    * @var string $url
    *
    * @ORM\Column(name="url", type="string", length=255, nullable=true)
    */
    private $url;
    /**
    * @var string $alt
    *
    * @ORM\Column(name="alt", type="string", length=255, nullable=true)
    */
    private $alt;

        /**
         * @var \DateTime
         *
         * @ORM\Column(name="dateEnregistrement", type="datetime", nullable=true)
         */
        private $dateEnregistrement;

    public function __construct() {
            $this->updateDate();
            $this->preUpload();
            $this->upload();
//            $this->preRemoveUpload();
//            $this->removeUpload();
        }

    // Les getters et setters

        /**
         * Get id
         *
         * @return integer 
         */
        public function getId()
        {
            return $this->id;
        }

        /**
         * Set url
         *
         * @param string $url
         * @return FileRequete
         */
        public function setUrl($url)
        {
            $this->url = $url;

            return $this;
        }

        /**
         * Get url
         *
         * @return string 
         */
        public function getUrl()
        {
            return $this->url;
        }

        /**
         * Set alt
         *
         * @param string $alt
         * @return FileRequete
         */
        public function setAlt($alt)
        {
            $this->alt = $alt;

            return $this;
        }

        /**
         * Get alt
         *
         * @return string 
         */
        public function getAlt()
        {
            return $this->alt;
        }

        /**
         * Set dateEnregistrement
         *
         * @param \DateTime $dateEnregistrement
         * @return FileRequete
         */
        public function setDateEnregistrement($dateEnregistrement)
        {
            $this->dateEnregistrement = $dateEnregistrement;

            return $this;
        }
        /**
         * Get dateEnregistrement
         *
         * @return \DateTime 
         */
        public function getDateEnregistrement()
        {
            return $this->dateEnregistrement;
        }
        /**
        * @ORM\PreUpdate
        * @ORM\PrePersist
        */
        public function updateDate()
        {
            $this->setDateEnregistrement(new \Datetime());
        }

       private $file;

       // On ajoute cet attribut pour y stocker le nom du fichier temporairement
        private $tempFilename;
        // On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre
        public function setFile(UploadedFile  $file)
        {
        $this->file = $file;
        // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->url) 
            {
            // On sauvegarde l'extension du fichier pour le supprimer plus tard
            $this->tempFilename = $this->url;
            // On réinitialise les valeurs des attributs url et alt
            $this->url = null;
            $this->alt = null;
            }
        }

        public function getFile()
        {
            return $this->file;
        }
        /**
        * @ORM\PrePersist()
        * @ORM\PreUpdate()
        */
        public function preUpload()
        {
            // Si jamais il n'y a pas de fichier (champ facultatif)
            if (null === $this->file) {
            return;
    //            $file= new UploadedFile("C:\wamp\www\Symfony\web\user.jpg", "user.jpg");
    //            $this->setFile($file);
            }
            // Le nom du fichier est son id, on doit juste stocker également son extension
            // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
            $this->url = $this->file->guessExtension();
            // Et on génère l'attribut alt de la balise <Requete>, à la valeur du nom du fichier sur le PC de l'internaute
            $this->alt = $this->file->getClientOriginalName();
            }
            /**
            * @ORM\PostPersist()
            * @ORM\PostUpdate()
            */
            public function upload()
            {
                // Si jamais il n'y a pas de fichier (champ facultatif)
                if (null === $this->file) {
                return;
                }
                // Si on avait un ancien fichier, on le supprime
                if (null !== $this->tempFilename) {
                    $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
                    if (file_exists($oldFile)) {
                    unlink($oldFile);
                }
            }
            // On déplace le fichier envoyé dans le répertoire de notre choix
            $this->file->move(
            $this->getUploadRootDir(), // Le répertoire de destination
            $this->id.'.'.$this->url // Le nom du fichier à créer, ici « id.extension »
            );
        }
        /**
        * @ORM\PreRemove()
        */
        public function preRemoveUpload()
        {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
        }
        /**
        * @ORM\PostRemove()
        */
        public function removeUpload()
        {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
        // On supprime le fichier
        unlink($this->tempFilename);
        }
        }
        public function getUploadDir()
        {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'uploads/Message';
        }
        protected function getUploadRootDir()
        {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
        }
        
        public function getNameFile()
        {
           return $this->getAlt();
        }

        // …
        public function getWebPath()
        {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
        }
        // …
        public function getDowloadPath()
        {
        return 'uploads/Message/'.$this->getId().'.'.$this->getUrl();
        }
    
}

src/BZ/BlogBundle/Entity/Recepteur.php
<?php

namespace BZ\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Recepteur
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="BZ\BlogBundle\Entity\RecepteurRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Recepteur
{
    /**
    * @ORM\ManyToOne(targetEntity="BZ\UserBundle\Entity\User")
    * @ORM\JoinColumn(nullable=true) 
    */
    private $user;
    
    /**
    * @ORM\ManyToOne(targetEntity="BZ\BlogBundle\Entity\Message", inversedBy="recepteurs")
    * @ORM\JoinColumn(nullable=true) 
    */
    private $message;
    
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datepersist", type="datetime", nullable=true)
     */
    private $datepersist;
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datedelete", type="datetime", nullable=true)
     */
    private $datedelete;

    /**
     * @var boolean
     * 
     * @ORM\Column(name="estdelete", type="boolean", nullable=true)
     */
    private $estdelete;
    
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateLu", type="datetime", nullable=true)
     */
    private $dateLu;

    /**
     * @var boolean
     * 
     * @ORM\Column(name="estLu", type="boolean", nullable=true)
     */
    private $estLu;
    
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set user
     *
     * @param \BZ\UserBundle\Entity\User $user
     * @return Recepteur
     */
    public function setUser(\BZ\UserBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \BZ\UserBundle\Entity\User 
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set message
     *
     * @param \BZ\BlogBundle\Entity\Message $message
     * @return Recepteur
     */
    public function setMessage(\BZ\BlogBundle\Entity\Message $message = null)
    {
        $this->message = $message;

        return $this;
    }

    /**
     * Get message
     *
     * @return \BZ\BlogBundle\Entity\Message 
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Set datedelete
     *
     * @param \DateTime $datedelete
     * @return Recepteur
     */
    public function setDatedelete($datedelete)
    {
        $this->datedelete = $datedelete;

        return $this;
    }

    /**
     * Get datedelete
     *
     * @return \DateTime 
     */
    public function getDatedelete()
    {
        return $this->datedelete;
    }

    /**
     * Set estdelete
     *
     * @param boolean $estdelete
     * @return Recepteur
     */
    public function setEstdelete($estdelete)
    {
        $this->estdelete = $estdelete;

        return $this;
    }

    /**
     * Get estdelete
     *
     * @return boolean 
     */
    public function getEstdelete()
    {
        return $this->estdelete;
    }

    /**
     * Set dateLu
     *
     * @param \DateTime $dateLu
     * @return Recepteur
     */
    public function setDateLu($dateLu)
    {
        $this->dateLu = $dateLu;

        return $this;
    }

    /**
     * Get dateLu
     *
     * @return \DateTime 
     */
    public function getDateLu()
    {
        return $this->dateLu;
    }

    /**
     * Set estLu
     *
     * @param boolean $estLu
     * @return Recepteur
     */
    public function setEstLu($estLu)
    {
        $this->estLu = $estLu;

        return $this;
    }

    /**
     * Get estLu
     *
     * @return boolean 
     */
    public function getEstLu()
    {
        return $this->estLu;
    }
    
      /**
    * @ORM\PrePersist
    */
   public function avantEnregistrement()
   {
     $this->setEstdelete(false);
     $this->setEstLu(false);
     $this->setDatedelete(null);
     $this->setDateLu(null);
     $this->setDatepersist(new \ Datetime());
   }
   

    /**
     * Set datepersist
     *
     * @param \DateTime $datepersist
     * @return Recepteur
     */
    public function setDatepersist($datepersist)
    {
        $this->datepersist = $datepersist;

        return $this;
    }

    /**
     * Get datepersist
     *
     * @return \DateTime 
     */
    public function getDatepersist()
    {
        return $this->datepersist;
    }
    
    public function getNomPrenom()
    {
        return $this->getUser()->getNomPrenom();
    }
}

src/BZ/BlogBundle/Form/MessageType.php
<?php

namespace BZ\BlogBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Doctrine\ORM\EntityRepository;

class MessageType extends AbstractType
{
//    private $id;
//     public function __construct($id)
//        {
//            $this->id = $id;
//        }
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
//        $id=$this->id;
        $builder
           
//          ->add('recepteurs','entity', array('label' => 'A (destinataires)', 
//                'class' => 'BZUserBundle:User',
//                'property' => 'nomPrenom',
//                'empty_value' => '',
//                'multiple' => true,
//                'attr' =>array('class' =>'form-control chzn-select'),
//                'required' => true,
//                'query_builder' => function(EntityRepository $er )  use ($id)
//                        {
//                                return $er->createQueryBuilder('u')
//                                        ->where('u.locked = 0')
//                                        ->andwhere('u.id not like :id')
//                                        ->setParameter('id',$id);
//                        }
//                        ))  
                        
             ->add('objet', 'text', array('label' => 'Objet', 'attr' =>array('class' =>'form-control')))           
                        
             ->add('messageEnvoi','textarea',array('label' => 'Contenu du Message', 'required' => true,'attr' =>array('class' =>'form-control')))           
       
             ->add('filerequete', new FileRequeteType(),array('label' => false, 'required' => false))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'BZ\BlogBundle\Entity\Message'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'bz_modelbundle_message';
    }
}

src/BZ/BlogBundle/Resources/views/Message/detail_emetteur.html.twig
{% extends "BZBlogBundle::parent_info.html.twig"%}

{% block parentAction %} 
    {{ path('detail_emetteur',{'id': id})}}
{% endblock parentAction %}

{% block parentEnctype %}  
{% endblock parentEnctype %}

{% block parentTitre %} <i class="icon icon-envelope"> </i> DETAIL DU MESSAGE{% endblock parentTitre %}
{% block parentStyle %} style="position: relative; left: 500px; top: 199px;" {% endblock parentStyle %}
{% block parentContenu %}
    <div style="color: black;font-size: 12px;" class="well">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        
        Date d'envoi : <strong>{{  element.message.dateEnvoi|date('d-m-Y') }} à {{  element.message.dateEnvoi|date('H:i') }}</strong><br/>
        Objet : <strong>{{  element.message.objet }}</strong><br/>
        Pièce Jointe : {% if element.message.filerequete is null %} <strong> Aucune</strong>{% else %}<a href="{{ asset( element.message.filerequete.dowloadPath) }}" target="_blank"><strong> {{ element.message.filerequete.nameFile }} </strong></a>{% endif %}<br/>
        Recepteur(s) : <strong>{% for recept in  element.message.recepteurs %}{{  recept.nomPrenom }} ; {% endfor %}</strong><br/>
        Texte du message : <br/><span style="margin-left: 10px;"> {{ element.message.messageEnvoi }} </span><br/>
    </div>
    
{% endblock parentContenu %}

src/BZ/BlogBundle/Resources/views/Message/detail_recepteur.html.twig
{% extends "BZBlogBundle::parent_info.html.twig"%}

{% block parentAction %} 
    {{ path('detail_recepteur',{'id': id})}}
{% endblock parentAction %}

{% block parentEnctype %}  
{% endblock parentEnctype %}
{% block parentTitre %} <i class="icon icon-envelope"> </i> DETAIL DU MESSAGE{% endblock parentTitre %}
{% block parentStyle %} style="position: relative; left: 500px; top: 199px;" {% endblock parentStyle %}
{% block parentContenu %}
    <div style="color: black;font-size: 12px;" class="well">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        Date reçue : <strong>{{  element.message.dateEnvoi|date('d-m-Y') }} à {{  element.message.dateEnvoi|date('H:i') }}</strong><br/>
        Objet : <strong>{{  element.message.objet }}</strong><br/>
        Pièce Jointe : {% if element.message.filerequete is null %} <strong> Aucune</strong>{% else %}<a href="{{ asset( element.message.filerequete.dowloadPath) }}" target="_blank"><strong> {{ element.message.filerequete.nameFile }} </strong></a>{% endif %}<br/>
        Emetteur : <strong>{{  element.message.emetteur.user.nomPrenom }} </strong><br/>
        Texte du message : <br/><span style="margin-left: 10px;"> {{ element.message.messageEnvoi }} </span><br/>
    </div>
  
{% endblock parentContenu %}

src/BZ/BlogBundle/Resources/views/Message/messages_envoye.html.twig
{% extends "BZUserBundle::layout.html.twig"%}
{% block content_title %} 
    <h6 style="text-align: center;text-shadow: 0px 0.5px 0.5px blue;">  BOÎTE DE MESSAGERIE </h6>
{% endblock content_title %}
{% block content_body %}
    <div class="col-lg-12" style="margin-top: 1%;">
        <div class="panel panel-default">
            
            <div class="panel-body">
                <span style="font-size: 12px;"> BOÎTE D'ENVOI DE MESSAGES</span> 
                <a href="{{ path('messages_ecrire') }}" style="float: right;margin-right: 5px;color: black;" class="btn btn-default  btn-xs btn-rect createformulaire" data-toggle="modal" data-target="#myModalu" > <i class="icon   icon-edit-sign"></i> Ecrire </a>                
                <a href="{{ path('messages_envoye') }}" style="float: right;margin-right: 5px;color: black;" class="btn btn-success  btn-xs btn-rect" > <i class="icon   icon-upload"> </i> Boîte d'envoi <i class="icon   icon-envelope-alt"> </i> </a>                
                <a href="{{ path('messages_recu') }}" style="float: right;margin-right: 5px;color: black;" class="btn btn-primary  btn-xs btn-rect" > <i class="icon   icon-download"> </i>  Boîte de reception <i class="icon   icon-envelope-alt"></i></a>                
                <hr/>
                <div class="table-responsive">
                    <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                        <table style="color: black;" class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example" aria-describedby="dataTables-example_info">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_desc" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" aria-sort="descending" style="font-size: 13px;text-align: center;">
                                        #
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="font-size: 13px;text-align: center;">
                                        Date Envoi
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="font-size: 13px;text-align: center;">
                                        Recepteur(s)
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="font-size: 13px;text-align: center;">
                                        Objet
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="font-size: 13px;text-align: center;">
                                        P J
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% set nbre = 0 %}
                                {% for element in  messages %}
                                     <tr class="gradeA {% if nbre%2==0 %} odd {% else %} even{% endif%}">
                                        {% set nbre = nbre+1 %}
                                        <td class="sorting_1" style="text-align: center;">
                                            <a href="{{ path('supprime_emetteur',{'id': element.id }) }}" title="Supprimer le message" class="btn btn-danger btn-xs btn-rect createformulaire" data-toggle="modal" data-target="#myModalu" style="font-size: 11px;"><i class="icon icon-remove"> </i> </a>
                                            <a href="{{ path('detail_emetteur',{'id': element.id }) }}" title="Voir plus de détail" class="btn btn-default btn-xs btn-rect createformulaire" data-toggle="modal" data-target="#myModalu" style="font-size: 11px;"><i class="icon icon-align-center"> </i> </a>
                                          </td>
                                        <td class="" style="font-size: 12px;">{{  element.message.dateEnvoi|date('d-m-Y') }} à {{  element.message.dateEnvoi|date('H:i') }}  </td>
                                        <td class="" style="font-size: 12px;max-width: 20%;"> {% for recept in  element.message.recepteurs %}{{  recept.nomPrenom }} ; {% endfor %}</td>
                                        <td class="" style="font-size: 12px;">{{  element.message.objet }} </td>
                                        <td class="" style="font-size: 12px;">
                                            {% if element.message.filerequete is null %} <strong> Aucune</strong>{% else %}<a href="{{ asset( element.message.filerequete.dowloadPath) }}" target="_blank"><strong> {{ element.message.filerequete.nameFile }} </strong></a>{% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div id='afficheformulaire'>

    </div>
{% endblock content_body %}
{% block javascript %} 
    <script>
        // Notifications();      
        $('.createformulaire').click(function (event) {
            var buton = $(this);
            $('#afficheformulaire').html('');
            $.ajax({
                type: 'GET',
                url: buton.attr('href'),
                cache: false,
                success: function (data) {
                    $('#afficheformulaire').html(data);
                    // $('#frm_createVille').dialog();
                },
                error: function () {
                    alert('requête échouée');
                }});
            //we dont what the browser to submit the form
            event.preventDefault();
        });

    </script>
{% endblock javascript %}

src/BZ/BlogBundle/Resources/views/Message/messages_recu.html.twig
{% extends "BZUserBundle::layout.html.twig"%}
{% block content_title %} 
    <h6 style="text-align: center;text-shadow: 0px 0.5px 0.5px blue;">  BOÎTE DE MESSAGERIE </h6>
{% endblock content_title %}
{% block content_body %}
    <div class="col-lg-12" style="margin-top: 1%;">
        <div class="panel panel-default">
            
            <div class="panel-body">
                <span style="font-size: 12px;"> BOÎTE DE RECEPTION DE MESSAGES</span> 
                <a href="{{ path('messages_ecrire') }}" style="float: right;margin-right: 5px;color: black;" class="btn btn-default  btn-xs btn-rect createformulaire" data-toggle="modal" data-target="#myModalu" > <i class="icon   icon-edit-sign"></i> Ecrire </a>                
                <a href="{{ path('messages_envoye') }}" style="float: right;margin-right: 5px;color: black;" class="btn btn-success  btn-xs btn-rect" > <i class="icon   icon-upload"> </i> Boîte d'envoi <i class="icon   icon-envelope-alt"> </i> </a>                
                <a href="{{ path('messages_recu') }}" style="float: right;margin-right: 5px;color: black;" class="btn btn-primary  btn-xs btn-rect" > <i class="icon   icon-download"> </i>  Boîte de reception <i class="icon   icon-envelope-alt"></i></a>                
                <hr/>
                <div class="table-responsive">
                    <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                        <table style="color: black;" class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example" aria-describedby="dataTables-example_info">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_desc" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" aria-sort="descending" style="font-size: 13px;text-align: center;">
                                        #
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="font-size: 13px;text-align: center;">
                                        Date Reçue
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="font-size: 13px;text-align: center;">
                                        Emetteur
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="font-size: 13px;text-align: center;">
                                        Lu ?
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="font-size: 13px;text-align: center;">
                                        Objet
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="font-size: 13px;text-align: center;">
                                        P J
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% set nbre = 0 %}
                                {% for element in  messages %}
                                     <tr class="gradeA {% if nbre%2==0 %} odd {% else %} even{% endif%}">
                                        {% set nbre = nbre+1 %}
                                        <td class="sorting_1" style="text-align: center;">
                                            <a href="{{ path('supprime_recepteur',{'id': element.id}) }}" title="Supprimer le message" class="btn btn-danger btn-xs btn-rect createformulaire" data-toggle="modal" data-target="#myModalu" style="font-size: 11px;"><i class="icon icon-remove"> </i> </a>
                                            <a href="{{ path('detail_recepteur',{'id': element.id}) }}" title="Voir plus de détail" class="btn btn-default btn-xs btn-rect createformulaire" data-toggle="modal" data-target="#myModalu" style="font-size: 11px;"><i class="icon icon-align-center"> </i> </a>
                                            <a href="{{ path('repondre_recepteur',{'id': element.id}) }}" title="Répondre au message" class="btn btn-info btn-xs btn-rect createformulaire" data-toggle="modal" data-target="#myModalu" style="font-size: 11px;"><i class="icon icon-share"> </i> </a>
                                          </td>
                                        <td class="" style="font-size: 12px;">{{  element.message.dateEnvoi|date('d-m-Y') }} à {{  element.message.dateEnvoi|date('H:i') }}  </td>
                                        <td class="" style="font-size: 12px;">{{  element.message.emetteur.user.nomPrenom }} </td>
                                        <td class="" style="font-size: 12px;text-align: center;">
                                               {%if element.estLu==1 %}
                                                    <div class="checkbox"><label><div class="checker disabled"><span class="checked"><input class="uniform" value="option3" checked="checked" disabled="disabled" type="checkbox"></span></div> </label></div>
                                                    {% else %}
                                                   <div class="checkbox"><label><div class="checker disabled"><span><input class="uniform" value="option2" disabled="disabled" type="checkbox"></span></div> </label></div>
                                                   {% endif %}
                                        </td>
                                        <td class="" style="font-size: 12px;">{{  element.message.objet }} </td>
                                        <td class="" style="font-size: 12px;">
                                            {% if element.message.filerequete is null %} <strong> Aucune</strong>{% else %}<a href="{{ asset( element.message.filerequete.dowloadPath) }}" target="_blank"><strong> {{ element.message.filerequete.nameFile }} </strong></a>{% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div id='afficheformulaire'>

    </div>
{% endblock content_body %}
{% block javascript %} 
    <script>
        // Notifications();      
        $('.createformulaire').click(function (event) {
            var buton = $(this);
            $('#afficheformulaire').html('');
            $.ajax({
                type: 'GET',
                url: buton.attr('href'),
                cache: false,
                success: function (data) {
                    $('#afficheformulaire').html(data);
                    // $('#frm_createVille').dialog();
                },
                error: function () {
                    alert('requête échouée');
                }});
            //we dont what the browser to submit the form
            event.preventDefault();
        });

    </script>
{% endblock javascript %}