src/BZ/BlogBundle/Entity/FileRequete.php
<?php
// src/BZ/BlogBundle/Entity/FileRequete.php
namespace BZ\BlogBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
// N'oubliez pas ce use :
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
* BZ\BlogBundle\Entity\FileRequete
*
* @ORM\Table()
* @ORM\Entity(repositoryClass="BZ\BlogBundle\Entity\FileRequeteRepository")
* @ORM\HasLifecycleCallbacks
*/
class FileRequete
{

    /**
    * @var integer $id
    *
    * @ORM\Column(name="id", type="integer")
    * @ORM\Id
    * @ORM\GeneratedValue(strategy="AUTO")
    */
    private $id;
    /**
    * @var string $url
    *
    * @ORM\Column(name="url", type="string", length=255, nullable=true)
    */
    private $url;
    /**
    * @var string $alt
    *
    * @ORM\Column(name="alt", type="string", length=255, nullable=true)
    */
    private $alt;

        /**
         * @var \DateTime
         *
         * @ORM\Column(name="dateEnregistrement", type="datetime", nullable=true)
         */
        private $dateEnregistrement;

    public function __construct() {
            $this->updateDate();
            $this->preUpload();
            $this->upload();
//            $this->preRemoveUpload();
//            $this->removeUpload();
        }

    // Les getters et setters

        /**
         * Get id
         *
         * @return integer 
         */
        public function getId()
        {
            return $this->id;
        }

        /**
         * Set url
         *
         * @param string $url
         * @return FileRequete
         */
        public function setUrl($url)
        {
            $this->url = $url;

            return $this;
        }

        /**
         * Get url
         *
         * @return string 
         */
        public function getUrl()
        {
            return $this->url;
        }

        /**
         * Set alt
         *
         * @param string $alt
         * @return FileRequete
         */
        public function setAlt($alt)
        {
            $this->alt = $alt;

            return $this;
        }

        /**
         * Get alt
         *
         * @return string 
         */
        public function getAlt()
        {
            return $this->alt;
        }

        /**
         * Set dateEnregistrement
         *
         * @param \DateTime $dateEnregistrement
         * @return FileRequete
         */
        public function setDateEnregistrement($dateEnregistrement)
        {
            $this->dateEnregistrement = $dateEnregistrement;

            return $this;
        }
        /**
         * Get dateEnregistrement
         *
         * @return \DateTime 
         */
        public function getDateEnregistrement()
        {
            return $this->dateEnregistrement;
        }
        /**
        * @ORM\PreUpdate
        * @ORM\PrePersist
        */
        public function updateDate()
        {
            $this->setDateEnregistrement(new \Datetime());
        }

       private $file;

       // On ajoute cet attribut pour y stocker le nom du fichier temporairement
        private $tempFilename;
        // On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre
        public function setFile(UploadedFile  $file)
        {
        $this->file = $file;
        // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->url) 
            {
            // On sauvegarde l'extension du fichier pour le supprimer plus tard
            $this->tempFilename = $this->url;
            // On réinitialise les valeurs des attributs url et alt
            $this->url = null;
            $this->alt = null;
            }
        }

        public function getFile()
        {
            return $this->file;
        }
        /**
        * @ORM\PrePersist()
        * @ORM\PreUpdate()
        */
        public function preUpload()
        {
            // Si jamais il n'y a pas de fichier (champ facultatif)
            if (null === $this->file) {
            return;
    //            $file= new UploadedFile("C:\wamp\www\Symfony\web\user.jpg", "user.jpg");
    //            $this->setFile($file);
            }
            // Le nom du fichier est son id, on doit juste stocker également son extension
            // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
            $this->url = $this->file->guessExtension();
            // Et on génère l'attribut alt de la balise <Requete>, à la valeur du nom du fichier sur le PC de l'internaute
            $this->alt = $this->file->getClientOriginalName();
            }
            /**
            * @ORM\PostPersist()
            * @ORM\PostUpdate()
            */
            public function upload()
            {
                // Si jamais il n'y a pas de fichier (champ facultatif)
                if (null === $this->file) {
                return;
                }
                // Si on avait un ancien fichier, on le supprime
                if (null !== $this->tempFilename) {
                    $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
                    if (file_exists($oldFile)) {
                    unlink($oldFile);
                }
            }
            // On déplace le fichier envoyé dans le répertoire de notre choix
            $this->file->move(
            $this->getUploadRootDir(), // Le répertoire de destination
            $this->id.'.'.$this->url // Le nom du fichier à créer, ici « id.extension »
            );
        }
        /**
        * @ORM\PreRemove()
        */
        public function preRemoveUpload()
        {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
        }
        /**
        * @ORM\PostRemove()
        */
        public function removeUpload()
        {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
        // On supprime le fichier
        unlink($this->tempFilename);
        }
        }
        public function getUploadDir()
        {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'uploads/Message';
        }
        protected function getUploadRootDir()
        {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
        }
        
        public function getNameFile()
        {
           return $this->getAlt();
        }

        // …
        public function getWebPath()
        {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
        }
        // …
        public function getDowloadPath()
        {
        return 'uploads/Message/'.$this->getId().'.'.$this->getUrl();
        }
    
}

src/BZ/BlogBundle/Entity/Recepteur.php
<?php

namespace BZ\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Recepteur
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="BZ\BlogBundle\Entity\RecepteurRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Recepteur
{
    /**
    * @ORM\ManyToOne(targetEntity="BZ\UserBundle\Entity\User")
    * @ORM\JoinColumn(nullable=true) 
    */
    private $user;
    
    /**
    * @ORM\ManyToOne(targetEntity="BZ\BlogBundle\Entity\Message", inversedBy="recepteurs")
    * @ORM\JoinColumn(nullable=true) 
    */
    private $message;
    
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datepersist", type="datetime", nullable=true)
     */
    private $datepersist;
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datedelete", type="datetime", nullable=true)
     */
    private $datedelete;

    /**
     * @var boolean
     * 
     * @ORM\Column(name="estdelete", type="boolean", nullable=true)
     */
    private $estdelete;
    
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateLu", type="datetime", nullable=true)
     */
    private $dateLu;

    /**
     * @var boolean
     * 
     * @ORM\Column(name="estLu", type="boolean", nullable=true)
     */
    private $estLu;
    
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set user
     *
     * @param \BZ\UserBundle\Entity\User $user
     * @return Recepteur
     */
    public function setUser(\BZ\UserBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \BZ\UserBundle\Entity\User 
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set message
     *
     * @param \BZ\BlogBundle\Entity\Message $message
     * @return Recepteur
     */
    public function setMessage(\BZ\BlogBundle\Entity\Message $message = null)
    {
        $this->message = $message;

        return $this;
    }

    /**
     * Get message
     *
     * @return \BZ\BlogBundle\Entity\Message 
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Set datedelete
     *
     * @param \DateTime $datedelete
     * @return Recepteur
     */
    public function setDatedelete($datedelete)
    {
        $this->datedelete = $datedelete;

        return $this;
    }

    /**
     * Get datedelete
     *
     * @return \DateTime 
     */
    public function getDatedelete()
    {
        return $this->datedelete;
    }

    /**
     * Set estdelete
     *
     * @param boolean $estdelete
     * @return Recepteur
     */
    public function setEstdelete($estdelete)
    {
        $this->estdelete = $estdelete;

        return $this;
    }

    /**
     * Get estdelete
     *
     * @return boolean 
     */
    public function getEstdelete()
    {
        return $this->estdelete;
    }

    /**
     * Set dateLu
     *
     * @param \DateTime $dateLu
     * @return Recepteur
     */
    public function setDateLu($dateLu)
    {
        $this->dateLu = $dateLu;

        return $this;
    }

    /**
     * Get dateLu
     *
     * @return \DateTime 
     */
    public function getDateLu()
    {
        return $this->dateLu;
    }

    /**
     * Set estLu
     *
     * @param boolean $estLu
     * @return Recepteur
     */
    public function setEstLu($estLu)
    {
        $this->estLu = $estLu;

        return $this;
    }

    /**
     * Get estLu
     *
     * @return boolean 
     */
    public function getEstLu()
    {
        return $this->estLu;
    }
    
      /**
    * @ORM\PrePersist
    */
   public function avantEnregistrement()
   {
     $this->setEstdelete(false);
     $this->setEstLu(false);
     $this->setDatedelete(null);
     $this->setDateLu(null);
     $this->setDatepersist(new \ Datetime());
   }
   

    /**
     * Set datepersist
     *
     * @param \DateTime $datepersist
     * @return Recepteur
     */
    public function setDatepersist($datepersist)
    {
        $this->datepersist = $datepersist;

        return $this;
    }

    /**
     * Get datepersist
     *
     * @return \DateTime 
     */
    public function getDatepersist()
    {
        return $this->datepersist;
    }
    
    public function getNomPrenom()
    {
        return $this->getUser()->getNomPrenom();
    }
}

src/BZ/BlogBundle/Controller/TchatController.php
<?php
// src/BZ/BlogBundle/Controller/BlogController.php
namespace BZ\BlogBundle\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\SecurityContext;
use Symfony\Component\HttpFoundation\Response;
use BZ\BlogBundle\Entity\Message;
use BZ\BlogBundle\Entity\Emetteur;
use BZ\BlogBundle\Entity\Recepteur;
use Doctrine\ORM\EntityRepository;

class TchatController extends Controller
{
    
    public function consulter_boiteAction($id)
    {
       $messages= $this->getDoctrine()
                                      ->getManager()->getRepository('BZBlogBundle:Message')
                                      ->findBy(Array('objet'=>'discussion'),Array('dateEnvoi'=>'ASC'));
        return $this->render('BZBlogBundle:Tchat:palette_tchat.html.twig', 
        array('menu_num'=> 2, 'id'=> $id, 'messages'=> $messages));
    }
    
    public function consulter_boiteautreAction($id)
    {
       $messages= $this->getDoctrine()
                                      ->getManager()->getRepository('BZBlogBundle:Message')
                                      ->findBy(Array('objet'=>'discussion'),Array('dateEnvoi'=>'ASC'));
        return $this->render('BZBlogBundle:Tchat:consulter_boite.html.twig', 
        array('menu_num'=> 2, 'id'=> $id, 'messages'=> $messages));
    }
    
    public function envoyer_msgAction($id)
    {
            $request = $this->get('request');
            if ($request->getMethod() == 'POST') 
            {
                $em = $this->getDoctrine()->getManager();
                $messagerecus= $this->getDoctrine()
                                      ->getManager()->getRepository('BZBlogBundle:Recepteur')
                                      ->findBy(Array('estdelete'=>false, 'user'=>  $this->getUser()->getId()));
                foreach ($messagerecus as $i){
                       if($i->getMessage()->getObjet()=='discussion' && $i->getMessage()->getEmetteur()->getUser()->getId()==$id){
                            $i->setEstLu(true);
                       }       
                  }
                $em->flush();
                $emetteur=new Emetteur;
                $emetteur->setUser($this->getUser());
                $message = new Message;
                $message->setEmetteur($emetteur);
                $message->setDateEnvoi(new \ Datetime());
                $message->setObjet('discussion');
                $message->setMessageEnvoi($_POST['messageTexte']);
                $recepteur = new Recepteur;
                $recepteur->setUser($this->getDoctrine() ->getManager()->getRepository('BZUserBundle:User')->find($id));       
                //$em = $this->getDoctrine()->getManager();
                $message->addRecepteur($recepteur);
                $em->persist($message);
                $em->flush();
                 $response = new Response(json_encode(array('rep' => 'ok')));
                $response->headers->set('Content-Type', 'application/json');
                return $response; 
        }
//                      
    }
   
}

src/BZ/BlogBundle/Resources/views/Tchat/consulter_boite.html.twig
<div class="panel-body" id="consulterboite">
    {% for msg in  messages %}
        <ul class="chat">
            {% if msg.emetteur.user.id == app.user.id %}
                {% set rep = 0 %}
                {% for recep in  msg.recepteurs %}
                    {% if recep.user.id == id %}
                        {% set rep = 1 %}
                    {% endif %}    
                {% endfor %}
                {% if rep == 1%}
                    <li class="left clearfix">
                        <span class="chat-img pull-left">
                            <img src="{% if msg.emetteur.user is not null %}{% if msg.emetteur.user.image is not null %} {{ asset(msg.emetteur.user.image.webPath) }} {% else %} {{ asset('uploads/img/user.jpg') }} {% endif %}{% else %} {{ asset('uploads/img/user.jpg') }} {% endif %}" style="height: 32px;width: 32px;" class="img-circle" alt="Photo de l'émetteur"/>
                        </span>
                        <div class="chat-body clearfix">
                            <div class="header">
                                <strong class="primary-font "> {{ msg.emetteur.user.nomPrenom }} </strong>
                                <small class="pull-right text-muted label label-default">
                                    <i class="icon-time"></i>  {{ msg.dateEnvoi | date('d/m/Y') }} à {{ msg.dateEnvoi | date('H:i') }}
                                </small>
                            </div>
                            <br>
                            <p style="font-size: 11px;">
                                {{ msg.messageEnvoi }}  
                            </p>
                        </div>
                    </li>
                {% endif %}
            {% endif %}
            {% if msg.emetteur.user.id == id %}
                {% set rep = 0 %}
                {% for recep in  msg.recepteurs %}
                    {% if recep.user.id == app.user.id %}
                        {% set rep = 1 %}
                    {% endif %}    
                {% endfor %}
                {% if rep == 1%}
                    <li class="right clearfix">
                        <span class="chat-img pull-right">
                            <img src="{% if msg.emetteur.user is not null %}{% if msg.emetteur.user.image is not null %} {{ asset(msg.emetteur.user.image.webPath) }} {% else %} {{ asset('uploads/img/user.jpg') }} {% endif %}{% else %} {{ asset('uploads/img/user.jpg') }} {% endif %}" style="height: 32px;width: 32px;" class="img-circle" alt="Photo de l'émetteur"/>
                        </span>
                        <div class="chat-body clearfix">
                            <div class="header">
                                <small class=" text-muted label label-info">
                                    <i class="icon-time"></i> {{ msg.dateEnvoi | date('d/m/Y') }} à {{ msg.dateEnvoi | date('H:i') }}</small>
                                <strong class="pull-right primary-font"> {{ msg.emetteur.user.nomPrenom }}</strong>
                            </div>
                            <br>
                            <p style="font-size: 11px;">
                                {{ msg.messageEnvoi }} 
                            </p>
                        </div>
                    </li>
                {% endif %}
            {% endif %}
        </ul>
    {% endfor %}
</div>

src/BZ/BlogBundle/Resources/views/Tchat/palette_tchat.html.twig
<div style="display: block;" class="modal fade in" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
    <form  class="ui-draggable"style="position: relative; left: 364px; top: 129px;" action="{{ path('envoyer_msg',{'id': id}) }}" method="post"  >

        <div class="col-lg-5">

            <div class="chat-panel panel panel-default">
                <div class="panel-heading">
                    <i class="icon-comments"></i>
                    Discussion instantannée
                    <a class="" id="btn-chat" href="#" onclick="location.reload();" style="float: right;">
                          <i class="icon-remove"></i>   </a>
                </div>
                <div class="panel-body" id="consulterboite">
                      {% for msg in  messages %}
                           <ul class="chat">
                            {% if msg.emetteur.user.id == app.user.id %}
                                 {% set rep = 0 %}
                                 {% for recep in  msg.recepteurs %}
                                         {% if recep.user.id == id %}
                                               {% set rep = 1 %}
                                         {% endif %}    
                                 {% endfor %}
                                 {% if rep == 1%}
                                 <li class="left clearfix">
                                    <span class="chat-img pull-left">
                                        <img src="{% if msg.emetteur.user is not null %}{% if msg.emetteur.user.image is not null %} {{ asset(msg.emetteur.user.image.webPath) }} {% else %} {{ asset('uploads/img/user.jpg') }} {% endif %}{% else %} {{ asset('uploads/img/user.jpg') }} {% endif %}" style="height: 32px;width: 32px;" class="img-circle" alt="Photo de l'émetteur"/>
                                    </span>
                                    <div class="chat-body clearfix">
                                        <div class="header">
                                            <strong class="primary-font "> {{ msg.emetteur.user.nomPrenom }} </strong>
                                            <small class="pull-right text-muted label label-default">
                                                <i class="icon-time"></i>  {{ msg.dateEnvoi | date('d/m/Y') }} à {{ msg.dateEnvoi | date('H:i') }}
                                            </small>
                                        </div>
                                        <br>
                                        <p style="font-size: 11px;" class="textMessage">
                                           {{ msg.messageEnvoi }}  
                                        </p>
                                    </div>
                                </li>
                               {% endif %}
                             {% endif %}
                         {% if msg.emetteur.user.id == id %}
                         {% set rep = 0 %}
                                 {% for recep in  msg.recepteurs %}
                                         {% if recep.user.id == app.user.id %}
                                               {% set rep = 1 %}
                                         {% endif %}    
                                 {% endfor %}
                          {% if rep == 1%}
                          <li class="right clearfix">
                            <span class="chat-img pull-right">
                                  <img src="{% if msg.emetteur.user is not null %}{% if msg.emetteur.user.image is not null %} {{ asset(msg.emetteur.user.image.webPath) }} {% else %} {{ asset('uploads/img/user.jpg') }} {% endif %}{% else %} {{ asset('uploads/img/user.jpg') }} {% endif %}" style="height: 32px;width: 32px;" class="img-circle" alt="Photo de l'émetteur"/>
                             </span>
                            <div class="chat-body clearfix">
                                <div class="header">
                                    <small class=" text-muted label label-info">
                                        <i class="icon-time"></i> {{ msg.dateEnvoi | date('d/m/Y') }} à {{ msg.dateEnvoi | date('H:i') }}</small>
                                    <strong class="pull-right primary-font"> {{ msg.emetteur.user.nomPrenom }}</strong>
                                </div>
                                <br>
                                <p style="font-size: 11px;" class="textMessage">
                                    {{ msg.messageEnvoi }} 
                                </p>
                            </div>
                        </li>
                        {% endif %}
                      {% endif %}
                     </ul>
                    {% endfor %}
                </div>
                <div class="panel-footer">
                    <div class="input-group">
                        <input id="btn-input" type="text" class="form-control input-sm" name="messageTexte" placeholder="Type your comment here...">
                        <span class="input-group-btn">
                            <button class="btn btn-success btn-sm" id="btn-chat">
                                Envoyer
                            </button>
                            <span class='tachat_img hide'><img src="{{ asset('/images/712.GIF') }}" alt="Second slide" class='img-circle' style="height: 20px;width: 20px;"> En cours ...</span>
                        </span>
                    </div>
                </div>

            </div>
  </div>
</form>
{% block parentScript %}
    <script>
        $('form').draggable();
        $("form").submit(function (event) {
            var $this = $(this);
            $('.tachat_img').removeClass('hide');
            $.ajax({
                type: $this.attr('method'),
                url: $this.attr('action'),
                cache: false,
                data: $this.serialize(),
                success: function () {
                    $('.tachat_img').addClass('hide');
                     $('#btn-input').val('');
                    message();
                    // location.reload();
                },
                error: function () {
                    // $('.tachat_img').removeClass('hide');
                }
            });
            //we dont what the browser to submit the form
            event.preventDefault();
        });
     $("#consulterboite").scrollTop( $("#consulterboite")[0].scrollHeight );
        function message(){
            $.ajax({
                     type: 'GET',
                     url: '{{ path('consulter_boiteautre',{'id': id}) }}',
                     cache: false,
                     data: null,
                     success: function (data) {
                         $('#consulterboite').replaceWith(data);
                         $("#consulterboite").scrollTop( $("#consulterboite")[0].scrollHeight );
                     
                     },
                     error: function () {
                         // $('.tachat_img').removeClass('hide');
                     }
                 });
         } 
         setInterval(message, 20000);     
    </script>
{% endblock parentScript %}
</div>